" ==========
" Sytanx and Indent
syntax on
set number
set cursorline
set ruler
set showcmd
set history=600

set autoindent
set smartindent
set expandtab
set smarttab
set tabstop=8
set shiftwidth=4
set softtabstop=4
set backspace=2
set t_Co=256


" ==========
" Search Conf
set ignorecase smartcase
set incsearch
set hlsearch
set showmatch


" ==========
" vim-plug
" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'ervandew/supertab'
" On-demand loading
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
Plug 'junegunn/fzf'

" Initialize plugin system
call plug#end()

" ale config
let g:airline#extensions#ale#enabled = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
