" ==========
" Sytanx and Indent
syntax on
set number
set cursorline
set ruler
set showcmd
set history=600

set autoindent
set smartindent
set expandtab
set smarttab
set tabstop=8
set shiftwidth=4
set softtabstop=4
set backspace=2
set t_Co=256

" ==========
" Search Conf
set ignorecase smartcase
set incsearch
set hlsearch

set showmatch

" ==========
" Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'ervandew/supertab'
Plugin 'vim-scripts/mru.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Lokaltog/vim-powerline'
Plugin 'scrooloose/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
